import Link from "next/link";
import "./globals.css";
import style from "./layout.module.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "한입시네마 앱라우터 버전",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <div className={style.container}>
          <header>
            <Link href={`${process.env.NEXT_PUBLIC_DEV_LINK}`}>
              ONEBITE CINEMA - app router version
            </Link>
          </header>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
